site_name: CRUD de Productos en Java
site_description: Documentación del sistema CRUD de productos en Java por consola.
site_author: Alejandro Melgar

theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

nav:
  - Inicio: index.md
  - Instalación y uso: instalacion.md
  - Operaciones CRUD: operaciones.md
  - Referencia de clases: referencia.md

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: es
      type: date

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
